Document: dauphine
Title: Debian dauphine Manual
Author: <insert document author here>
Abstract: This manual describes what dauphine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dauphine/dauphine.sgml.gz

Format: postscript
Files: /usr/share/doc/dauphine/dauphine.ps.gz

Format: text
Files: /usr/share/doc/dauphine/dauphine.text.gz

Format: HTML
Index: /usr/share/doc/dauphine/html/index.html
Files: /usr/share/doc/dauphine/html/*.html
